apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
namespace: easyclaim
images:
- name: easyclaim-backend-image
  newName: ikrushkov/my-project-backend
  newTag: "16"
