apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: easyclaim
resources:
- ./mysql
- ./backend
- ./frontend
- ingress.yaml
images:
- name: easyclaim-backend-image
  newName: ikrushkov/my-project-backend
  newTag: "16"
- name: easyclaim-frontend-image
  newName: ikrushkov/my-project-frontend
  newTag: 1.0.0-28
